### PR TITLE
Update translations into last version of Spanish DBD perks' names

### PR DESCRIPTION
**Pull request by jah0wl**
IDEM

### CODE REVIEW

**Comment by 3stadt** [comment]
Could you please change this so the word "Maleficio" is not included? It is kind of redundant and it will break the layout since the name gets to long.

grafik

You can see this yourself in the deploy preview above, which is generated for each Pull request. ;)

**Comment by jah0wl** [comment]
Oh Perfect. And how can we do it to make survivors (specially the newbie ones) find the perk properly, because as the "Hex:" perks, you can find them alphabetically, and if you don't know that's an Hex, you may turn crazy looking around.

**Comment by 3stadt** [comment]
From the top of my head possible solutions would be: Implement a search field that you can use to narrow down the visible perks or change the sorting and naming of the perks. Another option would be to change the UI so it can fit longer names.

All of this is currently not doable for me though, sadly.

**Comment by 3stadt** [comment]
Could you please rebase your branch and resolve the conflict? Then I will merge it. :)

**Comment by jah0wl** [comment]
I'm sorry but I don't know how to do this. My first time with github and I can't find how to resolve the conflicts or edit the patchs... :(

**Comment by 3stadt** [comment]
It was just one perk name as it seems. I resolved the conflict and merged your PR. Thank you for contributing! :-)

**Pull request merged**
